### ISSUE TITLE
Crash on start, return code 134

### ISSUE THREAD

**Issue by slve** [vv9k/epick#1]
Hi @wojciechkepka,

Thanks for sharing your application.
I installed it the first time, using Arch Linux,
When trying to run I get the following message and the app
returns with 134.
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
epick: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
[1]    43368 abort (core dumped)  epick
```
Tried both with and without running a composition manager, picom namely, got the same message and exit code.
My window manager is dwm.
Please let me know if there's more information I could provide to help debugging.

Thank you

**Comment by wojciechkepka** [comment]
Hi @slve,

thanks for checking the app out! I think it's a problem with the GUI library used here. There is a similar issue created here: https://github.com/emilk/egui/issues/446

For now I guess we'll have to wait a bit and see.

**Comment by slve** [comment]
Oh, great, thanks for the details!

**Comment by vv9k** [comment]
Seems like the upstream issue is already resolved so closing this one too.
