### ISSUE TITLE
Custom color display formats

### ISSUE THREAD

**Issue by crumblingstatue** [vv9k/epick#19]
Let the user define custom color display formats. For example, when working on an egui project, the user could simply define an egui color format `egui::Color32::from_rgb({r}, {g}, {b})`, which then can be easily copied to the clipboard with a click.

The design of the description language is yet to be decided, but I think a very simple basic language should be sufficient, maybe similar to the Rust format syntax.

Good to have features:
- [x] saveable across sessions
- [x] support decimal/hex (maybe octal, etc?) in the format syntax.

**Comment by vv9k** [comment]
Definitely a nice feature, would probably require some sort of persistent configuration file.
