### ISSUE TITLE
Dragging colours around causes a freeze

### ISSUE THREAD

**Issue by atagen** [vv9k/epick#44]
I've found that on my machine (Linux/X11) dragging a colour around to reorder it causes the whole application to become unresponsive. This happens on both native and web, premade and from source.

This isn't an actual crash, there's no panic or logs left behind if running from terminal. It seems to act as if the drag event has stalled the UI - cursor remains in "drag" state, no repaints occur and the rest of the application is totally blocked.

Please let me know if there's better information I could provide to help debug this. I find this tool very useful for exporting palettes and reordering them in epick UI before export is much nicer than any alternative.

**Comment by vv9k** [comment]
Thank you for this report, I was able to reproduce the issue and fix it in #45. Please let me know if the issue persists on your setup.

**Comment by atagen** [comment]
fixed for me - thank you!
