### ISSUE TITLE
Support for high res displays

### ISSUE THREAD

**Issue by sluedecke** [vv9k/epick#50]
epick is great, but it looks very small on a 2500x1440 display.

Can you add an option to scale the UI?

**Comment by vv9k** [comment]
Seems like a good idea. Will look into this soon when I get some free time.

**Comment by vv9k** [comment]
I've added some changes in #51 . There is a slider in settings now that will scale the whole UI. It has to be done manually for now as `egui` doesn't expose the current monitor size so it's not clear (for now) how to automatically adjust the scale.

**Comment by sluedecke** [comment]
That should do, many apps provide exactly such a slider. Thank you very much for it!
